
version: 2.1

jobs:
  run-python:
    docker:
      - image: "python:3.8"
    steps:
      - checkout
      - run:
          name: "run python"
          command: |
            python --version
            python pythonscript.py

workflows:
  say-hello-workflow:
    jobs:
      - run-python