
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run:
          name: "run python"
          command: |
          python python.py

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
